#!/bin/sh

while read file
    do
        case "$1" in
        "5")
            rm "$file" ;;
        
        "6")
            mv "$file" ~/p/fave ;;
        "7")
            mv "$file" ~/p/obg ;;
        esac
    done

